### ISSUE TITLE
Correct coding format

### ISSUE THREAD

**Issue by jakhuyen** [hw-design/base_components#1]
Do you know which one is the preferred coding method? I looked around and haven't found anything that states definitively one way or the other. I'm trying to detect a rising edge of an internal signal.

Method 1:
@ (posedge register)

Method 2:
if (posedge register)

**Comment by jakhuyen** [comment]
@ (posedge register) causes the Vivado synthesis tool to not display a critical warning, so that seems to be the best coding style.

**Comment by Joshua-Conner** [comment]
Looks like there is no expiration date with the modelsim student license. Four months and still working so far.
